# Generated by Django 6.0.7 on 2026-08-04 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='fa-calendar-days', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Douala', 'Douala'), ('Bafoussam', 'Bafoussam'), ('Garoua', 'Garoua'), ('Bamenda', 'Bamenda'), ('Buea', 'Buea'), ('Maroua', 'Maroua')], default='Yaoundé', max_length=100)),
                ('venue_name', models.CharField(help_text='e.g. Stade Ahmadou Ahidjo', max_length=200)),
                ('latitude', models.FloatField(default=3.8864, help_text='GPS Latitude')),
                ('longitude', models.FloatField(default=11.5367, help_text='GPS Longitude')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20)),
                ('entry_fee', models.CharField(default='Free', help_text='e.g. Free or 1,000 FCFA', max_length=100)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organizations.organizationprofile')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.sportscategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventcategory')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
