# Generated by Django 6.0.7 on 2026-09-04 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='USD', help_text='USD, EUR, FCFA, GBP', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_amount',
            field=models.PositiveIntegerField(default=0, help_text='Numeric entry fee for checkout (0 for free)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Global City', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.CharField(default='Free', help_text='e.g. Free, $25, or 5,000 FCFA', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=50, help_text='Maximum capacity of participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(help_text='e.g. Olympic Stadium, Madison Square Garden', max_length=200),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('team_or_club_name', models.CharField(blank=True, help_text='Athlete Team / Club / Independent', max_length=150)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed & Active'), ('PENDING_VALIDATION', 'Pending Organizer Validation'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'Payment Completed'), ('FREE', 'Free Registration'), ('PENDING', 'Payment Pending'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=30)),
                ('payment_method', models.CharField(default='CARD', help_text='Credit Card, PayPal, MTN MoMo, Orange Money, Apple Pay, Google Pay, Crypto', max_length=50)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('invoice_number', models.CharField(max_length=60, unique=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('organizer_validated', models.BooleanField(default=True, help_text='Organizer confirmation of registration')),
                ('organizer_validation_notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='EventAttendance',
        ),
    ]
