# Generated by Django 6.0.7 on 2026-09-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_feed', '0001_initial'),
        ('organizations', '0002_organizationprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='is_short',
            field=models.BooleanField(default=False, help_text='Is this a vertical short/reel story'),
        ),
        migrations.AddField(
            model_name='post',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='organizations.sportscategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media_feed/shorts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(default='Global City', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Space-separated hashtags e.g. #Football #Champions #Training', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('TEXT', 'Text Update'), ('IMAGE', 'Photo / Gallery'), ('VIDEO', 'Video Highlight'), ('SHORT', 'Sportiva Short / Reel'), ('ARTICLE', 'Article / Report')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, TikTok, or external video URL'),
        ),
    ]
