# Generated by Django 6.0.7 on 2026-08-04 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='fa-trophy', help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Sports Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Douala', 'Douala'), ('Bafoussam', 'Bafoussam'), ('Garoua', 'Garoua'), ('Bamenda', 'Bamenda'), ('Buea', 'Buea'), ('Maroua', 'Maroua')], default='Yaoundé', max_length=100)),
                ('address', models.CharField(help_text='Physical address or neighborhood', max_length=255)),
                ('latitude', models.FloatField(default=3.848, help_text='GPS Latitude for Leaflet Map')),
                ('longitude', models.FloatField(default=11.5021, help_text='GPS Longitude for Leaflet Map')),
                ('description', models.TextField(help_text='Overview of the club, academy, or facility')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp contact format e.g. +237699000000', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified profile badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
                ('sports_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organizations.sportscategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
