# Generated by Django 6.0.7 on 2026-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='country',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='address',
            field=models.CharField(help_text='Physical address, facility, or headquarters', max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='city',
            field=models.CharField(default='Global City', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='description',
            field=models.TextField(help_text='Overview of the club, academy, or training facility'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='latitude',
            field=models.FloatField(default=3.848, help_text='GPS Latitude for location popup'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='longitude',
            field=models.FloatField(default=11.5021, help_text='GPS Longitude for location popup'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact format e.g. +1... or +33... or +237...', max_length=30),
        ),
    ]
