# Generated by Django 6.0.7 on 2026-08-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='fa-box', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(help_text='Price in FCFA')),
                ('condition', models.CharField(choices=[('NEW', 'Brand New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good Condition'), ('FAIR', 'Fair Condition')], default='GOOD', max_length=20)),
                ('city', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Douala', 'Douala'), ('Bafoussam', 'Bafoussam'), ('Garoua', 'Garoua'), ('Bamenda', 'Bamenda'), ('Buea', 'Buea'), ('Maroua', 'Maroua')], default='Yaoundé', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
