# Generated by Django 6.0.7 on 2026-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='USD', help_text='USD, EUR, FCFA, GBP', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(default=3.8864, help_text='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(default=11.5367, help_text='GPS Longitude'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(default='Global City', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in local or selected currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
