# Generated by Django 6.0.7 on 2026-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_allowed_tabs',
            field=models.JSONField(blank=True, default=dict, help_text="Custom tab access overrides e.g. {'events': True, 'sponsorships': False}"),
        ),
    ]
