# Generated by Django 6.0.7 on 2026-09-04 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_custom_allowed_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Global', help_text='Country of residence / operations', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_sports',
            field=models.JSONField(blank=True, default=list, help_text="List of favorite sports/disciplines chosen by the user (e.g. ['Football', 'Basketball'])"),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle or link (@username or instagram.com/...)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, help_text='LinkedIn profile link', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, help_text='Telegram username or link (@username or t.me/...)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok',
            field=models.CharField(blank=True, help_text='TikTok handle (@username)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter/X handle or link (@username or x.com/...)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.CharField(blank=True, help_text='YouTube channel or link', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile image / Avatar', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Bio, athletic achievements or organizational overview'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Global City', help_text='City of residence / operations', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Direct phone / WhatsApp contact (with country code, e.g., +1..., +33..., +237...)', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ATHLETE', 'Athlete / Sports Enthusiast'), ('ORGANIZATION', 'Club / Academy / Organization / Manager'), ('TRAINER', 'Coach / Personal Trainer'), ('SPONSOR', 'Sponsor / Business Partner'), ('VISITOR', 'Visitor / Fan / Supporter')], default='ATHLETE', help_text='Primary role on Sportiva', max_length=20),
        ),
        migrations.CreateModel(
            name='AthleteExploit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., Top Scorer Champion's Cup 2026, 100m Gold Medalist", max_length=200)),
                ('category', models.CharField(choices=[('TITLE', 'Tournament / Championship Title'), ('MEDAL', 'Medal / Podium (Gold/Silver/Bronze)'), ('MVP', 'MVP / Best Player Award'), ('RECORD', 'Record / Personal Best / Exploit'), ('MATCH_WIN', 'Decisive Match / Tournament Victory'), ('CAPTAINCY', 'Captaincy / Leadership Exploit'), ('OTHER', 'Honor / Sports Achievement')], default='MEDAL', max_length=30)),
                ('competition_name', models.CharField(help_text='e.g. World Youth Games, National Championship', max_length=200)),
                ('date_achieved', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Details of the exploit, statistics, records, or match impact')),
                ('proof_image', models.ImageField(blank=True, help_text='Certificate, medal photo, or scoresheet', null=True, upload_to='exploits/')),
                ('proof_link', models.URLField(blank=True, help_text='Official results link or video evidence')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Validated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('validation_notes', models.TextField(blank=True, help_text='Verification verdict and notes from validating entity')),
                ('score_points', models.PositiveIntegerField(default=35, help_text='Merit score points granted upon verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploits', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, help_text='Coach, Club, Sponsor, or Organizer who verified this exploit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_exploits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_achieved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_or_merit', models.CharField(help_text='e.g. Tactical Vision, Speed, Leadership, Fair Play', max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to=settings.AUTH_USER_MODEL)),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('athlete', 'endorsed_by', 'skill_or_merit')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed_user')},
            },
        ),
    ]
