# Generated by Django 6.0.7 on 2026-08-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TRAVEL', 'Tournament Travel & Transport'), ('EQUIPMENT', 'Sports Equipment & Gear'), ('TRAINING', 'Training & Coaching Fees'), ('VENUE', 'Venue Rental & Logistics'), ('MEDICAL', 'Medical & Sports Insurance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('target_amount', models.PositiveIntegerField(help_text='Target amount in FCFA')),
                ('raised_amount', models.PositiveIntegerField(default=0, help_text='Amount raised so far in FCFA')),
                ('city', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Douala', 'Douala'), ('Bafoussam', 'Bafoussam'), ('Garoua', 'Garoua'), ('Bamenda', 'Bamenda'), ('Buea', 'Buea'), ('Maroua', 'Maroua')], default='Yaoundé', max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='sponsorships/')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Pledge amount in FCFA')),
                ('message', models.TextField(blank=True, help_text='Optional sponsor message')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='sponsorships.campaign')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
