# Generated by Django 6.0.7 on 2026-09-04 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_country_event_currency_event_fee_amount_and_more'),
        ('sponsorships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='latitude',
            field=models.FloatField(default=3.8864),
        ),
        migrations.AddField(
            model_name='campaign',
            name='longitude',
            field=models.FloatField(default=11.5367),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='city',
            field=models.CharField(default='Global City', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='raised_amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount raised so far'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_amount',
            field=models.PositiveIntegerField(help_text='Target amount (e.g. in FCFA or USD equivalent)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.PositiveIntegerField(help_text='Pledge amount'),
        ),
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('brand_tagline', models.CharField(blank=True, help_text='e.g. Empowering Next-Gen Global Champions', max_length=255)),
                ('industry', models.CharField(default='Sports Apparel & Nutrition', max_length=100)),
                ('annual_budget_range', models.CharField(default='$10,000 - $50,000 / 5M - 25M FCFA', help_text='Available sponsorship allocation', max_length=100)),
                ('sports_supported', models.JSONField(blank=True, default=list, help_text="Sports this sponsor invests in (e.g. ['Football', 'Athletics'])")),
                ('what_we_offer', models.TextField(help_text='What benefits the sponsor provides (e.g., Equipment, Financial Stipends, Travel Grants, Gear, Media Exposure)')),
                ('requirements_criteria', models.TextField(blank=True, help_text='What the sponsor looks for in athletes/events (e.g. Sportiva Score > 150, regional tournaments, social engagement)')),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(default='Global', max_length=100)),
                ('city', models.CharField(default='Global City', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(default=3.8864, help_text='GPS Latitude for location popup')),
                ('longitude', models.FloatField(default=11.5367, help_text='GPS Longitude for location popup')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('is_verified', models.BooleanField(default=True, help_text='Verified sponsor badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='e.g. SPT-CTR-2026-0042', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('financial_value', models.CharField(help_text='Contract value e.g. $15,000 / 7,500,000 FCFA', max_length=100)),
                ('terms_and_conditions', models.TextField(help_text='Detailed contractual obligations, branding rules, performance bonuses')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Proposal'), ('ACTIVE', 'Active & Enforced'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('sponsor_signed', models.BooleanField(default=True)),
                ('beneficiary_signed', models.BooleanField(default=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_contracts', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_contracts', to='events.event')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Proposal title e.g. Season 2026 Apparel & Travel Support', max_length=200)),
                ('proposal_type', models.CharField(choices=[('ATHLETE_TO_SPONSOR', 'Athlete / Club Requesting Sponsorship'), ('SPONSOR_TO_ATHLETE', 'Sponsor Offering Partnership / Deal'), ('EVENT_SPONSORSHIP', 'Event Sponsorship Proposal')], default='ATHLETE_TO_SPONSOR', max_length=30)),
                ('amount', models.CharField(help_text='Proposed financial value or gear valuation (e.g. $5,000 / 2,500,000 FCFA)', max_length=100)),
                ('deliverables_description', models.TextField(help_text='Detailed proposal, deliverables, branding placement, social exposure')),
                ('perks_offered', models.TextField(blank=True, help_text='Logo on jersey, event banner placement, VIP passes, social shoutouts')),
                ('status', models.CharField(choices=[('PENDING', 'Under Review / Pending'), ('ACCEPTED', 'Accepted / Agreed'), ('DECLINED', 'Declined'), ('CONVERTED_TO_CONTRACT', 'Converted to Contract')], default='PENDING', max_length=30)),
                ('response_message', models.TextField(blank=True, help_text='Feedback or counter-offer from recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorship_proposals', to='events.event')),
                ('recipient_athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_athlete_offers', to=settings.AUTH_USER_MODEL)),
                ('recipient_sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_sponsor_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
